-- Fidget.nvim highlights for Aether colorscheme
local M = {}

-- Import shared utility functions
local utils = require("aether.utils")
local hi = utils.hi

function M.setup(colors)
	-- Fidget progress
	hi("FidgetProgress", { fg = colors.base08 })
	hi("FidgetProgressDone", { fg = colors.base0D })
	hi("FidgetProgressTitle", { fg = colors.base08, style = "bold" })
	hi("FidgetProgressIcon", { fg = colors.base08 })
	hi("FidgetProgressGroup", { fg = colors.base0C })
	hi("FidgetProgressSubGroup", { fg = colors.base0A })
	hi("FidgetProgressMessage", { fg = colors.base05 })
	hi("FidgetProgressPercent", { fg = colors.base0C })
	hi("FidgetProgressSpinner", { fg = colors.base08 })
	hi("FidgetProgressText", { fg = colors.base05 })
	hi("FidgetProgressClient", { fg = colors.base0C })
	hi("FidgetProgressTodo", { fg = colors.base0A })
	hi("FidgetProgressError", { fg = colors.base08 })
	hi("FidgetProgressWarn", { fg = colors.base0A })
	hi("FidgetProgressInfo", { fg = colors.base0D })
	hi("FidgetProgressHint", { fg = colors.base0C })
	hi("FidgetProgressCancelled", { fg = colors.base03 })
	hi("FidgetProgressPending", { fg = colors.base0A })
	hi("FidgetProgressRunning", { fg = colors.base08 })
	hi("FidgetProgressSuccess", { fg = colors.base0D })
	hi("FidgetProgressFailed", { fg = colors.base08 })
	hi("FidgetProgressSkipped", { fg = colors.base03 })
	hi("FidgetProgressCanceled", { fg = colors.base03 })
	hi("FidgetProgressTimeout", { fg = colors.base08 })
	hi("FidgetProgressUnknown", { fg = colors.base03 })
	hi("FidgetProgressDefault", { fg = colors.base05 })
	hi("FidgetProgressActive", { fg = colors.base08, style = "bold" })
	hi("FidgetProgressInactive", { fg = colors.base03 })
	hi("FidgetProgressQuiet", { fg = colors.base03 })
	hi("FidgetProgressLoud", { fg = colors.base08, style = "bold" })
	hi("FidgetProgressSilent", { fg = colors.base03 })
	hi("FidgetProgressVerbose", { fg = colors.base05 })
	hi("FidgetProgressDebug", { fg = colors.base03 })
	hi("FidgetProgressTrace", { fg = colors.base03 })
	hi("FidgetProgressLog", { fg = colors.base05 })
	hi("FidgetProgressWindow", { fg = colors.base05, bg = colors.float_bg })
	hi("FidgetProgressBorder", { fg = colors.base03 })
	hi("FidgetProgressNormal", { fg = colors.base05 })
	hi("FidgetProgressHeader", { fg = colors.base08, style = "bold" })
	hi("FidgetProgressFooter", { fg = colors.base03 })
	hi("FidgetProgressSeparator", { fg = colors.base03 })
	hi("FidgetProgressBar", { fg = colors.base08, bg = colors.float_bg })
	hi("FidgetProgressBarFill", { fg = colors.base00, bg = colors.base08 })
	hi("FidgetProgressBarEmpty", { fg = colors.base03, bg = colors.float_bg })
	hi("FidgetProgressBarBorder", { fg = colors.base03 })
	hi("FidgetProgressBarText", { fg = colors.base05 })
	hi("FidgetProgressBarPercent", { fg = colors.base0C })
	hi("FidgetProgressBarSpinner", { fg = colors.base08 })
	hi("FidgetProgressBarTitle", { fg = colors.base08, style = "bold" })
	hi("FidgetProgressBarMessage", { fg = colors.base05 })
	hi("FidgetProgressBarClient", { fg = colors.base0C })
	hi("FidgetProgressBarIcon", { fg = colors.base08 })
	hi("FidgetProgressBarGroup", { fg = colors.base0C })
	hi("FidgetProgressBarSubGroup", { fg = colors.base0A })
	hi("FidgetProgressBarTodo", { fg = colors.base0A })
	hi("FidgetProgressBarError", { fg = colors.base08 })
	hi("FidgetProgressBarWarn", { fg = colors.base0A })
	hi("FidgetProgressBarInfo", { fg = colors.base0D })
	hi("FidgetProgressBarHint", { fg = colors.base0C })
	hi("FidgetProgressBarCancelled", { fg = colors.base03 })
	hi("FidgetProgressBarPending", { fg = colors.base0A })
	hi("FidgetProgressBarRunning", { fg = colors.base08 })
	hi("FidgetProgressBarSuccess", { fg = colors.base0D })
	hi("FidgetProgressBarFailed", { fg = colors.base08 })
	hi("FidgetProgressBarSkipped", { fg = colors.base03 })
	hi("FidgetProgressBarCanceled", { fg = colors.base03 })
	hi("FidgetProgressBarTimeout", { fg = colors.base08 })
	hi("FidgetProgressBarUnknown", { fg = colors.base03 })
	hi("FidgetProgressBarDefault", { fg = colors.base05 })
	hi("FidgetProgressBarActive", { fg = colors.base08, style = "bold" })
	hi("FidgetProgressBarInactive", { fg = colors.base03 })
	hi("FidgetProgressBarQuiet", { fg = colors.base03 })
	hi("FidgetProgressBarLoud", { fg = colors.base08, style = "bold" })
	hi("FidgetProgressBarSilent", { fg = colors.base03 })
	hi("FidgetProgressBarVerbose", { fg = colors.base05 })
	hi("FidgetProgressBarDebug", { fg = colors.base03 })
	hi("FidgetProgressBarTrace", { fg = colors.base03 })
	hi("FidgetProgressBarLog", { fg = colors.base05 })
end

return M
